import ip11 from "../img/iphone11-yellow-2019.jpg"
import ip12p from "../img/iphone-12-pro-blue-2020.jpg"
import s23u from "../img/a23ultra2.jpg"
import rn11p from "../img/redmi-note-11-pro-5g-6gb128gb.jpg"
import rn12s from "../img/xiaomi-redmi-note-12s-8256.jpg"
import zf4 from "../img/zfold4.jpg"
import fb5 from "../img/freebuds_5-silver_1_.jpg"
import ap2 from "../img/airpodspro2.jpg"
import apm from "../img/airpodsmax.png"
import b2p from "../img/buds2pro.jpg"
import mbd14 from "../img/matebook2.jpg"
export const ProductsData =[
    {
        id: 1,
        title: " iPhone 11 64GB - Yellow",
        description: "Descripcion del producto, descripcion del producto, descripcion del producto",
        price: 312000,
        discountPercentage: 10,
        rating: 4.69,
        stock: 94,
        brand: "Apple",
        category: "smartphones",
        thumbnail:"...",
        images: ip11,
    },
    {
        id: 2,
        title: "iPhone 12 Pro 128GB - Pacific Blue",
        description: "Descripcion del producto, descripcion del producto, descripcion del producto",
        price: 749990,
        discountPercentage: 15,
        rating: 4.69,
        stock: 94,
        brand: "Apple",
        category: "smartphones",
        thumbnail: "...",
        images: ip12p,
    },
    {
        id: 3,
        title: "Samsung S23 Ultra",
        description: "Descripcion del producto, descripcion del producto, descripcion del producto",
        price: 559990,
        discountPercentage: 10,
        rating: 4.69,
        stock: 94,
        brand: "Apple",
        category: "smartphones",
        thumbnail: "...",
        images: s23u,
    },
    {
        id: 4,
        title: "Redmi Note 11 Pro 5G",
        description: "Descripcion del producto, descripcion del producto, descripcion del producto",
        price: 185000,
        discountPercentage: 15,
        rating: 4.69,
        stock: 94,
        brand: "Apple",
        category: "smartphones",
        thumbnail: "...",
        images: rn11p,
    },
    {
        id: 5,
        title: "Xiaomi Redmi Note 12s 8GB 256GB",
        description: "Descripcion del producto, descripcion del producto, descripcion del producto",
        price: 162500,
        discountPercentage: 10,
        rating: 4.69,
        stock: 94,
        brand: "Apple",
        category: "smartphones",
        thumbnail: "...",
        images: rn12s,
    },
    {
        id: 6,
        title: "Samsung Galaxy Z Fold 4 256GB 12GB",
        description: "Descripcion del producto, descripcion del producto, descripcion del producto",
        price: 659990,
        discountPercentage: 12.96,
        rating: 4.69,
        stock: 94,
        brand: "Apple",
        category: "smartphones",
        thumbnail: "...",
        images: zf4,
    },
    {
        id: 7,
        title: "iPhone 11",
        description: "Descripcion del producto, descripcion del producto, descripcion del producto",
        price: 549,
        discountPercentage: 12.96,
        rating: 4.69,
        stock: 94,
        brand: "Apple",
        category: "smartphones",
        thumbnail: "...",
        images: ["...", "...", "..."],
    },
    {
        id: 8,
        title: "iPhone 11",
        description: "Descripcion del producto, descripcion del producto, descripcion del producto",
        price: 549,
        discountPercentage: 12.96,
        rating: 4.69,
        stock: 94,
        brand: "Apple",
        category: "smartphones",
        thumbnail: "...",
        images: ["...", "...", "..."],
    },
    {
        id: 9,
        title: "iPhone 11",
        description: "Descripcion del producto, descripcion del producto, descripcion del producto",
        price: 549,
        discountPercentage: 12.96,
        rating: 4.69,
        stock: 94,
        brand: "Apple",
        category: "smartphones",
        thumbnail: "...",
        images: ["...", "...", "..."],
    },
    {
        id: 10,
        title: "iPhone 11",
        description: "Descripcion del producto, descripcion del producto, descripcion del producto",
        price: 549,
        discountPercentage: 12.96,
        rating: 4.69,
        stock: 94,
        brand: "Apple",
        category: "smartphones",
        thumbnail: "...",
        images: ["...", "...", "..."],
    },
    {
        id: 11,
        title: "MateBook D 14 2021",
        description: "Descripcion del producto, descripcion del producto, descripcion del producto",
        price: 410000,
        discountPercentage: 12.96,
        rating: 4.69,
        stock: 94,
        brand: "Apple",
        category: "laptops",
        thumbnail: "...",
        images: mbd14,
    },
    {
        id: 12,
        title: "PC",
        description: "Descripcion del producto, descripcion del producto, descripcion del producto",
        price: 549,
        discountPercentage: 12.96,
        rating: 4.69,
        stock: 94,
        brand: "Apple",
        category: "laptops",
        thumbnail: "...",
        images: ["...", "...", "..."],
    },
    {
        id: 13,
        title: "PC",
        description: "Descripcion del producto, descripcion del producto, descripcion del producto",
        price: 549,
        discountPercentage: 12.96,
        rating: 4.69,
        stock: 94,
        brand: "Apple",
        category: "laptops",
        thumbnail: "...",
        images: ["...", "...", "..."],
    },
    {
        id: 14,
        title: "PC",
        description: "Descripcion del producto, descripcion del producto, descripcion del producto",
        price: 549,
        discountPercentage: 12.96,
        rating: 4.69,
        stock: 94,
        brand: "Apple",
        category: "laptops",
        thumbnail: "...",
        images: ["...", "...", "..."],
    },
    {
        id: 15,
        title: "PC",
        description: "Descripcion del producto, descripcion del producto, descripcion del producto",
        price: 549,
        discountPercentage: 12.96,
        rating: 4.69,
        stock: 94,
        brand: "Apple",
        category: "laptops",
        thumbnail: "...",
        images: ["...", "...", "..."],
    },
    {
        id: 16,
        title: "PC",
        description: "Descripcion del producto, descripcion del producto, descripcion del producto",
        price: 549,
        discountPercentage: 12.96,
        rating: 4.69,
        stock: 94,
        brand: "Apple",
        category: "laptops",
        thumbnail: "...",
        images: ["...", "...", "..."],
    },
    {
        id: 17,
        title: "PC",
        description: "Descripcion del producto, descripcion del producto, descripcion del producto",
        price: 549,
        discountPercentage: 12.96,
        rating: 4.69,
        stock: 94,
        brand: "Apple",
        category: "laptops",
        thumbnail: "...",
        images: ["...", "...", "..."],
    },
    {
        id: 18,
        title: "PC",
        description: "Descripcion del producto, descripcion del producto, descripcion del producto",
        price: 549,
        discountPercentage: 12.96,
        rating: 4.69,
        stock: 94,
        brand: "Apple",
        category: "laptops",
        thumbnail: "...",
        images: ["...", "...", "..."],
    },
    {
        id: 19,
        title: "HUAWEI FreeBuds 5",
        description: "Descripcion del producto, descripcion del producto, descripcion del producto",
        price: 95999,
        discountPercentage: 12.96,
        rating: 4.69,
        stock: 94,
        brand: "Apple",
        category: "headphones",
        thumbnail: "...",
        images: fb5,
    },
    {
        id: 20,
        title: "AirPods Pro (2nd generation)",
        description: "Descripcion del producto, descripcion del producto, descripcion del producto",
        price: 94999,
        discountPercentage: 12.96,
        rating: 4.69,
        stock: 94,
        brand: "Apple",
        category: "headphones",
        thumbnail: "...",
        images: ap2,
    },
    {
        id: 21,
        title: "AirPods Max",
        description: "Descripcion del producto, descripcion del producto, descripcion del producto",
        price: 359999,
        discountPercentage: 12.96,
        rating: 4.69,
        stock: 94,
        brand: "Apple",
        category: "headphones",
        thumbnail: "...",
        images: apm,
    },
    {
        id: 22,
        title: "Samsung Buds 2 Pro",
        description: "Descripcion del producto, descripcion del producto, descripcion del producto",
        price: 78999,
        discountPercentage: 12.96,
        rating: 4.69,
        stock: 94,
        brand: "Apple",
        category: "headphones",
        thumbnail: "...",
        images: b2p,
    }
]